// Auto-generated index.js - DO NOT EDIT MANUALLY
// This file is generated by build/generate-index.js
// To add a component, create it in src/components/ComponentName/ and run npm run build

// Import all components
const Button = require('./components/Button/Button.js');
const Checkbox = require('./components/Checkbox/Checkbox.js');
const CodeBlock = require('./components/CodeBlock/CodeBlock.js');
const Dropdown = require('./components/Dropdown/Dropdown.js');
const Form = require('./components/Form/Form.js');
const Icon = require('./components/Icon/Icon.js');
const Loader = require('./components/Loader/Loader.js');
const Menu = require('./components/Menu/Menu.js');
const MessageBox = require('./components/MessageBox/MessageBox.js');
const MetricItem = require('./components/MetricItem/MetricItem.js');
const ModalDialog = require('./components/ModalDialog/ModalDialog.js');
const Notification = require('./components/Notification/Notification.js');
const Section = require('./components/Section/Section.js');
const TabView = require('./components/TabView/TabView.js');
const TextBox = require('./components/TextBox/TextBox.js');
const Toggle = require('./components/Toggle/Toggle.js');

// Import all styles (except theming)
require('./index.css');

// Export components
const Dotbox = {
    Button,
    Checkbox,
    CodeBlock,
    Dropdown,
    Form,
    Icon,
    Loader,
    Menu,
    MessageBox,
    MetricItem,
    ModalDialog,
    Notification,
    Section,
    TabView,
    TextBox,
    Toggle,
};

// Global export for browser usage
if (typeof window !== 'undefined') {
    window.Dotbox = Dotbox;
}

// Module export for Node.js usage
module.exports = Dotbox;
